### ISSUE TITLE
Add platformer example

### ISSUE THREAD

**Issue by alessandrochl** [gamedevaton/phyzzle#1]
I'm not that good in physics, could you please add various examples? Phyzzle itself it's pretty good but I can't realize how to make platformer physics, or how to implement any other kind of physics except top-down movement.

**Comment by gamedevaton** [comment]
Thanks for the feedback, the next release will have an improved platformer example game, better code comments, documentation and guides. Hope this will help you make your game!

**Comment by gamedevaton** [comment]
Plaformer example added in v2.0.0
